{% set version = "0.7.1" %}

package:
  name: mknotebooks
  version: {{ version }}

source:
  # sdist not published to pypi
  url: https://github.com/greenape/mknotebooks/archive/refs/tags/{{ version }}.tar.gz
  sha256: 641dcf1721f89844f418aeefc8cc6f49a7faaa1ac14383714750d40ab5b02c8a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - nbconvert >=6.0.0
    - mkdocs >=1.1
    - markdown >=3.3.3
    - jupyter_client
    - gitpython
test:
  imports:
    - mknotebooks
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/greenape/mknotebooks
  summary: 'A plugin for mkdocs to help you include Jupyter notebooks in your projects'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
